sonar.projectKey=dummy-app
sonar.projectName=dummy-app
sonar.sources=web
sonar.host.url=http://localhost:9000
sonar.token=sqp_2bf88ccd3096a6fa5720208ff3ed968e9d44bd1e
sonar.tests=.
sonar.test.inclusions=**/*.test.js
