sonar.projectKey=dummy-app
sonar.projectName=dummy-app
sonar.sources=.
sonar.host.url=http://sonarqube:9000
sonar.token=sqp_2bf88ccd3096a6fa5720208ff3ed968e9d44bd1e
sonar.javascript.lcov.reportPaths=coverage/lcov.info