sonar.projectKey=dummy-app
sonar.projectName=dummy-app

sonar.sources=web
sonar.tests=web

sonar.test.inclusions=**/*.test.js
sonar.javascript.lcov.reportPaths=web/coverage/lcov.info

sonar.host.url=http://sonarqube:9000
sonar.token=sqp_2bf88ccd3096a6fa5720208ff3ed968e9d44bd1e
